# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_remove_show_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shows.Category'),
        ),
    ]
