# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_show_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='company_page',
            field=models.CharField(default='http://birminghamstage.com/shows/gangsta-granny-by-david-walliams-comes-to-the-stage', max_length=300),
            preserve_default=False,
        ),
    ]
