# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0008_auto_20170704_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
