# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0010_auto_20170705_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageelement',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='link',
            field=models.CharField(max_length=300),
        ),
    ]
