# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0012_remove_imageelement_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageelement',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
