# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0013_imageelement_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shows.Category')),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='site_live',
            field=models.BooleanField(default=False),
        ),
    ]
