# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0017_auto_20170705_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageelement',
            name='tag',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='imageelement',
            name='text_element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.TextElement'),
        ),
        migrations.AlterField(
            model_name='imageelement',
            name='show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.Show'),
        ),
        migrations.AlterField(
            model_name='imageelement',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
