# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0019_auto_20170706_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageelement',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
