# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import shows.models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0020_auto_20170706_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageelement',
            name='image',
            field=models.ImageField(upload_to=shows.models.photo_directory_path),
        ),
    ]
