# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 11:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0021_auto_20170707_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_published', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
