# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0022_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageelement',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.Post'),
        ),
        migrations.AlterField(
            model_name='textelement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.Category'),
        ),
    ]
