# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0025_auto_20170722_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shows.Show'),
        ),
    ]
